---
name: Build and release Jobs

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for different targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Create release tarballs
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p artifacts
          tar czf artifacts/${{ matrix.target }}-xray2junit.tar.gz \
            -C target/${{ matrix.target }}/release/ xray2junit

      - run: find artifacts
      - name: Upload builds
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: artifacts
          path: artifacts

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    name: Deploy to github
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - run: find artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.tar.gz
